{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "prompt = \"\"\"\n",
    "You are a friendly AI assistant, ForgeMind, who turns descriptions of CAD operations for AutoDesk Fusion into python scripts which perform the described operation.\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def read_file(file_path: str) -> str:\n",
    "    \"\"\"\n",
    "    Reads the content of a file and returns it as a string.\n",
    "    \n",
    "    Parameters:\n",
    "    file_path (str): The path to the file to be read.\n",
    "    \n",
    "    Returns:\n",
    "    str: The content of the file.\n",
    "    \"\"\"\n",
    "    content = ''\n",
    "    with open(file_path, 'r') as file:\n",
    "        content = file.read('text_to_fusion/unprocessed/${file_path}')\n",
    "    return content"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "dataset = [\n",
    "    {\n",
    "        \"user\": \"Create a cylinder with a radius of 5 and a height of 20\",\n",
    "        \"response\": read_file(\"cylinder.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"Create a 5x5x5 cube\",\n",
    "        \"response\": read_file(\"cube.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"Draw me an L shape with length 4 on both sides and a thickness of 2\",\n",
    "        \"response\": read_file(\"l_shape.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"Make a hollow cylinder with an outer radius of 2, inner radius of 1, and a height of 4\",\n",
    "        \"response\": read_file(\"hollow_cylinder.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"Design a rectangular prism with width 10, height 40, and depth 12\",\n",
    "        \"response\": read_file(\"rectangular_prism.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"Create a stop sign with side length 100 and depth 20\",\n",
    "        \"response\": read_file(\"stop_sign.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"Create a 5x5x5 cube with radius 3 circular hole through the middle\",\n",
    "        \"response\": read_file(\"cube_with_hole.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"Delete all bodies and sketches\",\n",
    "        \"response\": read_file(\"delete_all.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"Create a 10x10 square on the XZ plane\",\n",
    "        \"response\": read_file(\"square.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"Extrude my sketch by 2 units\",\n",
    "        \"response\": read_file(\"extrude.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"create 2 circles on the xz plane along the x axis that are 2 cm away from the origin with a radius of 3mm\",\n",
    "        \"response\": read_file(\"circles.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"fillet the edges of this body with a radius of 3mm\",\n",
    "        \"response\": read_file(\"fillet.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"draw a disk with a radius of 2cm centered at the origin along the xz plane, give it a thickness of 0.5 cm\",\n",
    "        \"response\": read_file(\"disk.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"create a circle with a diameter of 7.5cm on the xz plane, centered at the origin and give it a thickness of 0.5cm\",\n",
    "        \"response\": read_file(\"disk_diameter.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"create a hollow cylinder with an outer diameter of 7.5cm and a wall thickness of 0.5cm on the xz plane, and extrude 12cm along the z axis\",\n",
    "        \"response\": read_file(\"hollow_cylinder_2.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"create a circle about the origin on the xz plane with a diameter of 6.5cm and extrude 0.5cm along the z axis. Join it to my current body\",\n",
    "        \"response\": read_file(\"join_cylinder.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"fillet all my edges with a radius of 1mm\",\n",
    "        \"response\": read_file(\"fillet_all.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"change the radius of all my fillets to 2mm\",\n",
    "        \"response\": read_file(\"change_fillet_radius.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"remove all fillets\",\n",
    "        \"response\": read_file(\"remove_all_fillets.py\")\n",
    "    },\n",
    "    {\n",
    "        \"user\": \"Write 3D text that says 'YC'\",\n",
    "        \"response\": read_file(\"write_text.py\")\n",
    "    }\n",
    "]"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
